#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
set -euo pipefail

repo_root="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
variant="normal"
config=""
output=""
size="20G"
fs_label="guix-root"
mount_dir=""
install_dir=""
build_image=""
build_succeeded=0
external_mount=0
default_channels_file="$repo_root/config/channels.scm"
PATH="/usr/sbin:/sbin:$PATH"
export PATH

usage() {
    cat <<'EOF'
Usage: build-native-rootfs.sh [options]

Builds a native Guix System root image for Qubes.

Options:
  --variant NAME    Template variant: normal or minimal. Default: normal
  --config FILE     Guix operating-system file. Default depends on variant.
  --output FILE     Output ext4 image. Default: root.img or root-minimal.img
  --size SIZE       Image size passed to truncate. Default: 20G, matching the
                    current Qubes builder template-root-size default.
  --fs-label LABEL  ext4 filesystem label. Default: guix-root
  --install-dir DIR Install into an already-mounted root filesystem instead of
                    creating an image. Used by Builder v2 content scripts.
  -h, --help        Show this help.

Environment:
  GUIX_TIME_MACHINE Use guix time-machine for the system build. Default: 1.
                    Set to 0/no/false/off to use the host guix command.
  GUIX_CHANNELS_FILE
                    Optional channels.scm passed to guix time-machine -C.
                    Default: config/channels.scm.
  GUIX_BRANCH       Explicit developer override used only when no channels file
                    is available. Release builds should not use this.
EOF
}

die() {
    printf 'error: %s\n' "$*" >&2
    exit 1
}

need() {
    command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"
}

require_arg() {
    [ "$#" -ge 2 ] || die "$1 requires a value"
}

guix_system_command=()

set_guix_system_command() {
    case "${GUIX_TIME_MACHINE:-1}" in
        0|no|false|off)
            guix_system_command=(guix system)
            ;;
        *)
            if [ -n "${GUIX_CHANNELS_FILE:-}" ]; then
                [ -r "$GUIX_CHANNELS_FILE" ] ||
                    die "GUIX_CHANNELS_FILE is not readable: $GUIX_CHANNELS_FILE"
                guix_system_command=(guix time-machine -C "$GUIX_CHANNELS_FILE" -- system)
            elif [ -r "$default_channels_file" ]; then
                guix_system_command=(guix time-machine -C "$default_channels_file" -- system)
            elif [ -n "${GUIX_BRANCH:-}" ]; then
                guix_system_command=(guix time-machine "--branch=$GUIX_BRANCH" -- system)
            else
                die "missing pinned Guix channels file: $default_channels_file; set GUIX_CHANNELS_FILE or explicit developer-only GUIX_BRANCH"
            fi
            ;;
    esac
}

write_installed_config() {
    local tmp_config module

    tmp_config="$(mktemp)"
    {
        printf '%s\n' \
            ';; Self-contained native GNU Guix System Qubes TemplateVM config.' \
            ';; Generated by scripts/build-native-rootfs.sh so the installed' \
            ';; template can run: guix system reconfigure /etc/config.scm'
        for module in \
            "$repo_root/native/modules/qubes/packages/qubes-vm.scm" \
            "$repo_root/native/modules/qubes/services/qubes-vm.scm" \
            "$repo_root/native/modules/qubes/systems/guix-template.scm"
        do
            printf '\n;;; begin %s\n' "${module#"$repo_root/"}"
            sed 's/[[:space:]]*$//' "$module"
        done
        printf '\n;;; begin %s\n' "${config#"$repo_root/"}"
        sed 's/[[:space:]]*$//' "$config"
    } >"$tmp_config"

    sudo install -m 0644 "$tmp_config" "$mount_dir/etc/config.scm"
    rm -f "$tmp_config"
}

write_installed_channels() {
    local channels_file

    if [ -n "${GUIX_CHANNELS_FILE:-}" ]; then
        channels_file="$GUIX_CHANNELS_FILE"
    else
        channels_file="$default_channels_file"
    fi

    [ -r "$channels_file" ] || return 0
    sudo install -d -m 0755 "$mount_dir/etc/guix"
    sudo install -m 0644 "$channels_file" "$mount_dir/etc/guix/channels.scm"
}

cleanup() {
    if [ "$external_mount" -eq 0 ] && [ -n "$mount_dir" ] &&
        mountpoint -q "$mount_dir"; then
        sudo umount "$mount_dir"
    fi
    if [ "$external_mount" -eq 0 ] && [ -n "$mount_dir" ] &&
        [ -d "$mount_dir" ]; then
        rmdir "$mount_dir"
    fi
    if [ "$build_succeeded" -eq 0 ] && [ -n "$build_image" ] && [ -e "$build_image" ]; then
        rm -f "$build_image"
    fi
}
trap cleanup EXIT

while [ "$#" -gt 0 ]; do
    case "$1" in
        --variant)
            require_arg "$@"
            variant="$2"
            shift 2
            ;;
        --config)
            require_arg "$@"
            config="$2"
            shift 2
            ;;
        --output)
            require_arg "$@"
            output="$2"
            shift 2
            ;;
        --size)
            require_arg "$@"
            size="$2"
            shift 2
            ;;
        --fs-label)
            require_arg "$@"
            fs_label="$2"
            shift 2
            ;;
        --install-dir)
            require_arg "$@"
            install_dir="$2"
            shift 2
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            die "unknown argument: $1"
            ;;
    esac
done

case "$variant" in
    normal)
        : "${config:=$repo_root/native/qubes-guix.scm}"
        : "${output:=$repo_root/root.img}"
        ;;
    minimal)
        : "${config:=$repo_root/native/qubes-guix-minimal.scm}"
        : "${output:=$repo_root/root-minimal.img}"
        ;;
    *)
        die "unsupported variant: $variant"
        ;;
esac

need guix
need sudo
need mountpoint
if [ -z "$install_dir" ]; then
    need mkfs.ext4
fi
set_guix_system_command

[ -r "$config" ] || die "missing Guix system config: $config"

if [ -n "$install_dir" ]; then
    mount_dir="$install_dir"
    external_mount=1
    [ -d "$mount_dir" ] || die "install dir is not a directory: $mount_dir"
    mountpoint -q "$mount_dir" ||
        die "install dir is not a mount point: $mount_dir"
else
    mkdir -p "$(dirname -- "$output")"
    build_image="$(mktemp "$(dirname -- "$output")/.build-native-rootfs.XXXXXX.img")"
    truncate -s "$size" "$build_image"
    mkfs.ext4 -F -L "$fs_label" "$build_image"

    mount_dir="$(mktemp -d "$repo_root/mnt.XXXXXX")"
    sudo mount -o loop "$build_image" "$mount_dir"
fi

sudo "${guix_system_command[@]}" init --no-bootloader \
    -L "$repo_root/native/modules" "$config" "$mount_dir"
sudo test -x "$mount_dir/var/guix/profiles/system/profile/bin/sh" ||
    die "Guix system profile does not provide bin/sh"
sudo test -x "$mount_dir/var/guix/profiles/system/profile/bin/guile" ||
    die "Guix system profile does not provide bin/guile"
write_installed_config
write_installed_channels

sudo mkdir -p "$mount_dir/sbin" "$mount_dir/bin" "$mount_dir/lib/modules" "$mount_dir/var/run" "$mount_dir/run/qubes" "$mount_dir/run/qubes-service"
if ! sudo test "$mount_dir/var/run" -ef "$mount_dir/run" 2>/dev/null; then
    sudo rm -rf "$mount_dir/var/run/qubes" "$mount_dir/var/run/qubes-service"
    sudo rm -f "$mount_dir/var/run/qubes-service-environment"
    sudo ln -sfn /run/qubes "$mount_dir/var/run/qubes"
    sudo ln -sfn /run/qubes-service "$mount_dir/var/run/qubes-service"
    sudo ln -sfn /run/qubes-service-environment "$mount_dir/var/run/qubes-service-environment"
fi
sudo ln -sfn /var/guix/profiles/system/profile/bin/sh "$mount_dir/bin/sh"
sudo ln -sfn /var/guix/profiles/system/profile/bin/bash "$mount_dir/bin/bash"
sudo ln -sfn /var/guix/profiles/system/profile/sbin/halt "$mount_dir/sbin/poweroff"
sudo tee "$mount_dir/sbin/init" >/dev/null <<'EOF'
#!/var/guix/profiles/system/profile/bin/sh
profile=/var/guix/profiles/system/profile
PATH="$profile/bin:$profile/sbin${PATH:+:$PATH}"
GUIX_NEW_SYSTEM=/var/guix/profiles/system
export PATH
export GUIX_NEW_SYSTEM

"$profile/bin/mkdir" -p /proc /sys /dev /run/qubes /run/qubes-service /var/run
[ -e /proc/cmdline ] || "$profile/bin/mount" -n -t proc proc /proc || true
[ -e /sys/kernel ] || "$profile/bin/mount" -n -t sysfs sysfs /sys || true
[ -e /dev/null ] || "$profile/bin/mount" -n -t devtmpfs devtmpfs /dev || true
if ! "$profile/bin/test" /var/run -ef /run 2>/dev/null; then
    "$profile/bin/rm" -rf /var/run/qubes /var/run/qubes-service
    "$profile/bin/rm" -f /var/run/qubes-service-environment
    "$profile/bin/ln" -s /run/qubes /var/run/qubes
    "$profile/bin/ln" -s /run/qubes-service /var/run/qubes-service
    "$profile/bin/ln" -s /run/qubes-service-environment /var/run/qubes-service-environment
fi

exec "$profile/bin/guile" --no-auto-compile /var/guix/profiles/system/boot "$@"
EOF
sudo chmod 0755 "$mount_dir/sbin/init"
build_succeeded=1

if [ "$external_mount" -eq 0 ]; then
    sudo umount "$mount_dir"
    rmdir "$mount_dir"
    mount_dir=""
    mv -f "$build_image" "$output"
    printf 'native Guix root image written to %s\n' "$output"
else
    printf 'native Guix system installed into %s\n' "$mount_dir"
fi
